update_release_info:
  stage: deploy
  tags:
    - x86_64
  image: gitlab-registry.cern.ch/linuxsupport/alma8-base
  before_script:
    - dnf install -y git sshpass
  script:
    - |
      curl -X POST "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/releases" \
      --header "PRIVATE-TOKEN: ${CI_API_TOKEN}" \
      --header "Content-Type: application/json" \
      --data "{\"tag_name\": \"${CI_COMMIT_TAG}\", \"name\": \"${CI_COMMIT_TAG}\", \"description\": \"${CI_COMMIT_TAG_MESSAGE:-No release notes.}\", \"assets\": { \"links\": [{ \"name\": \"HEP Benchmark Suite Python3 wheels\", \"url\": \"${CI_WEB_RELEASES}/${CI_COMMIT_TAG}\", \"link_type\":\"other\" }] }}" \
      --fail --output "/dev/null" --silent --show-error --write-out "HTTP response: ${http_code:-OK}\n\n"
    - SSHPASS=${CI_CPUBMK} sshpass -v -e ssh -oStrictHostKeyChecking=no cpubmk@lxplus.cern.ch "echo ${CI_COMMIT_TAG} > ${CI_EOS_RELEASES}/latest"
  rules:
    - if: $CI_COMMIT_TAG =~ $PEP440_VERSION_REGEX && $CI_COMMIT_TAG !~ /.*rc[0-9].*/
